# Site settings
title: Calvin Alexander Knowlton
email: CalvinAKnowlton@gmail.com
description: The Jekyll version of the Highlights theme by HTML5 UP.
baseurl: "https://alexknowlton313.github.io"
url: ""

# Social settings
500px_url:
facebook_url: https://facebook.com/knowltona
github_url: https://github.com/AlexKnowlton313
gitlab_url: https://gitlab.com/Knowltona
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/calexknowlton
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
