# Custom Variables
title: Calvin Alexander Knowlton
email: CalvinAKnowlton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath
url: "https://alexknowlton313.github.io/" # the base hostname & protocol
twitter_username: alexknowlton313
github_username:  alexknowlton313
linkedIn_url: "https://www.linkedin.com/in/calexknowlton"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
