# Site settings
title: Highlights
email: youremailaddress@gmail.com
description: The Jekyll version of the Highlights theme by HTML5 UP.
baseurl: "/highlights-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: https://facebook.com/knowltona
github_url: https://github.com/AlexKnowlton313
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/calexknowlton
pinterest_url:
slack_url:
twitter_url: https://twitter.com/AlexKnowlton313

# Build settings
markdown: kramdown
